config/routes.rb
Rails.application.routes.draw do
  resources :games
  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :playables, dependent: :destroy
  has_many :users, through: :playables

  enum state: {
    in_progress: 'in_progress',
    checkmate: 'checkmate',
    draw: 'draw'
  }

  enum turn: {
    white: 'white',
    black: 'black'
  }

  before_create :set_fen
  before_create :set_pgn

  def set_fen
    turn_abbreviation = white? ? 'w' : 'b'
    self.fen = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR #{turn_abbreviation} KQkq - 0 1"
  end

  def set_pgn
    self.pgn =
'
[Event "Casual Game"]
[Site "Localhost"]
[Date "01/20/23"]
[EventDate "?"]
[Round "?"]
[Result "1-0"]
[White "?"]
[Black "?"]
[ECO "?"]
[WhiteElo "?"]
[BlackElo "?"]
[PlyCount "?"]
'
  end

  def orientation(user)
    white_player_id == user.id ? 'white' : 'black'
  end
end

app/models/playable.rb
class Playable < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :playables
  has_many :games, through: :playables

  def game_in_progress_with(target_user)
    games.where(id: target_user.games, state: "in_progress")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/color_concerns.rb
module ColorConcerns
  extend ActiveSupport::Concern

  def get_colors(color_choice)
    case color_choice
    when 'white'
      :white
    when 'black'
      :black
    else
      %i[white black].sample
    end
  end

  def assign_colors
    color_choice = get_colors(params[:game][:color])
    if color_choice == :white
      params[:game][:white_player_id] = params[:game][:challenger_id]
      params[:game][:black_player_id] = params[:game][:challengee_id]
    else
      params[:game][:white_player_id] = params[:game][:challengee_id]
      params[:game][:black_player_id] = params[:game][:challenger_id]
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[show edit update destroy]
  before_action :authenticate_user!
  include ColorConcerns

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show; end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit; end

  # POST /games or /games.json
  def create
    assign_colors
    @game = Game.new(
      turn: :white,
      state: :in_progress,
      white_player_id: params[:game][:white_player_id],
      black_player_id: params[:game][:black_player_id]
    )

    respond_to do |format|
      if @game.save
        Playable.create(game: @game, user_id: params[:game][:challenger_id])
        Playable.create(game: @game, user_id: params[:game][:challengee_id])
        format.html { redirect_to game_url(@game), notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(
      :color,
      :challenger_id,
      :challengee_id
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @users = User.where.not(id: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/games/_board.html.erb
<%= content_tag(:div, "", data: {
    controller: "chess",
    "chess-game-id-value": game.id,
    "chess-player-id-value": current_user.id,
    "chess-fen-value": game.fen,
    "chess-turn-value": game.turn[0],
    "chess-orientation-value": game.orientation(current_user)
}, style: "width: 400px") do %>
  <div id="board"></div>
  <strong>State:</strong>
  <%= content_tag(:div, "", data: {
      chess_target: "state"
    }) do %>
    <%= game.state %>
  <% end %>
  <%= content_tag(:div, "", data: {
      chess_target: "fen"
    }) do %>
    <%= game.fen %>
  <% end %>
<% end %>

app/views/games/_challenge_button.html.erb
<div class="container">
  <%= form_with model: Game.new, url: games_path, method: :post do |form| %>
    <div class="row form-group mb-5">
      <%= form.hidden_field :challenger_id, value: current_user.id %>
      <%= form.hidden_field :challengee_id, value: user.id %>
      <div class="col-4 p-0">
        <%= content_tag(:span, "#{user.email}", class:"input-group-text w-100") %>
      </div>
      <div class="col-4 p-0">
        <%= form.select :color, 
          options_for_select([['White', 'white'], ['Black', 'black'], ['Random', 'random']],
          ),{}, {class:"form-select w-100"} %>
      </div>
      <div class="col-4 p-0">
        <%= form.submit "Challenge", class:"btn btn-primary w-100" %>
      </div>
    </div>
  <% end %>
</div>

app/views/games/_form.html.erb
<%= simple_form_for(@game) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :state %>
    <%= f.input :turn %>
    <%= f.input :fen %>
    <%= f.input :pgn %>
    <%= f.input :white_player_id %>
    <%= f.input :black_player_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <div class="row">
    <div class="col-8">
      <%= render partial: "games/board", locals: {game:game} %>
    </div>
    <div class="col-4">
      <%= render partial: "games/pgn", locals: {game:game} %>
    </div>
  </div>
</div>

app/views/games/_pgn.html.erb
<%= turbo_frame_tag dom_id(game, "pgn") do %>
  <h1>PGN</h1>
  <div>
    <pre class="pgn" id="<%= dom_id(game, "pre_pgn") %>"><%= game.pgn %></pre>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Games</h1>

<div id="games">
  <% @games.each do |game| %>
    <%= render game %>
    <p>
      <%= link_to "Show this game", game %>
    </p>
  <% end %>
</div>

<%= link_to "New game", new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @game %>

<div>
  <%= link_to "Edit this game", edit_game_path(@game) %> |
  <%= link_to "Back to games", games_path %>

  <%= button_to "Destroy this game", @game, method: :delete %>
</div>

app/views/layouts/_players.html.erb
<% @users.each do |user| %>
  <% games = current_user.game_in_progress_with(user) %>
  <p>You are playing with <%= user.email %> <%= games.count %> games</p>
  <% games.each do |game| %>
    <%= link_to "Continue Game", game_path(game) %>
  <% end %>
  <%= render partial: "games/challenge_button", locals: { user: user }%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChessBro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Chess Bro</h1>
<% if current_user %>
  <h3><%= current_user.email %></h3>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  <%= render partial: "layouts/players" %>
<% else %>
  <%= link_to 'Login', new_user_session_path %>
  <%= link_to 'sign_up', new_user_registration_path %>
<% end %>